# Generated by Django 4.1.1 on 2022-09-24 11:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimbVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=100)),
                (
                    "degree",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(70),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(19),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("upload_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("video", models.FileField(blank=True, upload_to="")),
                ("start_time", models.TimeField(blank=True)),
                ("end_time", models.TimeField(blank=True)),
                ("success", models.BooleanField(blank=True)),
            ],
        ),
    ]
