# Generated by Django 4.1.1 on 2022-09-23 14:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimbVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="")),
                ("title", models.CharField(max_length=100)),
                (
                    "degree",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(70),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(19),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("upload_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
