# Generated by Django 4.1.1 on 2022-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kilterboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climbvideo",
            name="upload_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
