# Generated by Django 4.1.2 on 2022-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kilterboard", "0003_holddetectionmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holddetectionmodel",
            name="model_path",
            field=models.FileField(upload_to=""),
        ),
    ]
