name: Django CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: loging wandb
      run: |
        wandb login ${{ secrets.WANDB_TOKEN }}
    - name: Run Tests
      run: |
        sudo apt update
        sudo apt install ffmpeg
        python manage.py test
        flake8 *.py
        
